---
layout: post
title: "macOSでPythonからMeCabを使おうとすると /usr/local/etc/mecabrc が見つからないと出るとき"
tags: Qiita
---
この記事はQiitaに投稿されたものの転載です。

---
## 前提

Homebrewで`mecab`と`mecab-ipadic`を、pipで`mecab-python3`をインストールしている。

```
% brew install mecab
% brew install mecab-ipadic
% pip install mecab-python3
```
Pythonのプログラムで`MeCab`を使用している。

```py:xxx.py
import MeCab
tagger = MeCab.Tagger()
...
```

## エラー内容

Pythonプログラムを実行すると以下のような例外が投げられる。

```
----------------------------------------------------------

Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/SamuraiT/mecab-python3#common-issues

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/SamuraiT/mecab-python3/issues

issueを英語で書く必要はありません。

------------------- ERROR DETAILS ------------------------
arguments: 
default dictionary path: None
[ifs] no such file or directory: /usr/local/etc/mecabrc
----------------------------------------------------------
```

## 原因

MeCabの辞書へのパスがHomebrewでインストールされた場所を指していない。

## 解決方法

環境変数に `MECABRC=/opt/homebrew/etc/mecabrc` を設定する。

```
% MECABRC=/opt/homebrew/etc/mecabrc python xxx.py
```

## 環境
macOS Sonoma Version 14.0

`% brew list --versions`
mecab 0.996
mecab-ipadic 2.7.0-20070801

`% python --version`
Python 3.11.4
